version: '3.9'

services:
  app:
    image: ruby:3.1.2
    container_name: ssn-api
    tty: true
    env_file:
      - .env
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    depends_on:
      - postgres
    entrypoint: ./entrypoint.sh
    command: "bundle exec rails s -b 0.0.0.0"

  postgres:
    image: postgres
    container_name: ssn-db
    environment:
      POSTGRES_DB: primarydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  rubygems:
  database:
